# -*- coding: utf-8 -*-
"""facial_attribute_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysJzI0CGic_PZ14QVXCgBjKlGsxmQa9z
"""

# Verify that CUDA is available and that Google Colab assigned a GPU.
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

# Install InsightFace and the GPU version of ONNX Runtime
!pip install insightface onnxruntime-gpu

import cv2
import matplotlib.pyplot as plt
from insightface.app import FaceAnalysis

# Initialize FaceAnalysis and force it to use the GPU (ctx_id=0 targets the first GPU)
app = FaceAnalysis(providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640))

print("InsightFace successfully initialized on GPU!")

import cv2
import os
from tqdm import tqdm  # Visual progress bar

def process_and_save_dataset(input_dir, output_dir, insightface_app):
    """
    Scans the input directory, detects faces, applies a 15% padding,
    resizes them to 224x224, and saves them to the output directory.
    """
    # Create target directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Filter image files
    valid_extensions = ('.png', '.jpg', '.jpeg')
    files = [f for f in os.listdir(input_dir) if f.lower().endswith(valid_extensions)]
    print(f"Found {len(files)} images to process in '{input_dir}'")

    # Added tqdm here for a clean progress bar instead of infinite text flooding
    for filename in tqdm(files, desc="Processing images via GPU"):
        img_path = os.path.join(input_dir, filename)
        img = cv2.imread(img_path)

        if img is None:
            continue

        # 1. Face Detection
        faces = insightface_app.get(img)
        if not faces:
            continue

        # Extract the primary face
        face = faces[0]

        # 2. Strict Preprocessing Logic (15% Padding)
        x1, y1, x2, y2 = face.bbox.astype(int)
        h, w = img.shape[:2]

        face_width = x2 - x1
        face_height = y2 - y1

        padding_x = int(face_width * 0.15)
        padding_y = int(face_height * 0.15)

        x1 = max(0, x1 - padding_x)
        y1 = max(0, y1 - padding_y)
        x2 = min(w, x2 + padding_x)
        y2 = min(h, y2 + padding_y)

        face_img = img[y1:y2, x1:x2]
        face_img = cv2.resize(face_img, (224, 224))

        # 3. Save the processed 224x224 crop
        output_path = os.path.join(output_dir, filename)
        cv2.imwrite(output_path, face_img)

    print("\nProcessing complete!")

from google.colab import files
uploaded = files.upload()
process_and_save_dataset(input_dir=".", output_dir="processed_faces", insightface_app=app)

import os
import json

# 1. Input your Kaggle credentials directly
KAGGLE_USERNAME = input("Enter your Kaggle Username: ").strip()
KAGGLE_KEY = input("Enter your Kaggle API Key: ").strip()

# 2. Automatically create the structure expected by the system
kaggle_data = {"username": KAGGLE_USERNAME, "key": KAGGLE_KEY}

os.makedirs(os.path.expanduser("~/.kaggle"), exist_ok=True)
with open(os.path.expanduser("~/.kaggle/kaggle.json"), "w") as f:
    json.dump(kaggle_data, f)

# Set secure permissions
os.chmod(os.path.expanduser("~/.kaggle/kaggle.json"), 0o600)
print("\nKaggle credentials configured successfully from API Key!")

# 3. Download the dataset directly
print("\nDownloading CelebA dataset...")
!kaggle datasets download -d jessicali9530/celeba-dataset

# 4. Extract files
print("\nExtracting dataset... (this takes about a minute)")
!mkdir -p celeba_dataset
!unzip -q celeba-dataset.zip -d celeba_dataset

# 5. Clean up zip
!rm celeba-dataset.zip
print("\nDownload and extraction complete!")

# 6. Verify files
img_dir = "celeba_dataset/img_align_celeba/img_align_celeba"
if os.path.exists(img_dir):
    print(f"SUCCESS: Found {len(os.listdir(img_dir))} images in the directory.")

process_and_save_dataset(
    input_dir="celeba_dataset/img_align_celeba/img_align_celeba",
    output_dir="processed_celeba_faces",
    insightface_app=app
)

import pandas as pd

# Load attributes (Kaggle extracted it as a CSV file)
attr_df = pd.read_csv("celeba_dataset/list_attr_celeba.csv")

# Keep only Image name and the 'Smiling' attribute
smiling_df = attr_df[['image_id', 'Smiling']].copy()

# Convert Kaggle's (-1) labels to (0) for standard binary classification
smiling_df['Smiling'] = smiling_df['Smiling'].replace(-1, 0)

print(smiling_df.head())

# Get list of successfully processed images on your disk
processed_images = set(os.listdir("processed_celeba_faces"))

# Filter the dataframe to match only existing files
final_dataset_df = smiling_df[smiling_df['image_id'].isin(processed_images)].reset_index(drop=True)

print(f"Total labeled images ready for training: {len(final_dataset_df)}")







import torch
import torch.nn as nn
from torchvision.models import mobilenet_v3_large, MobileNet_V3_Large_Weights

def get_smile_model():
    # Load pre-trained MobileNetV3 Large
    weights = MobileNet_V3_Large_Weights.DEFAULT
    model = mobilenet_v3_large(weights=weights)

    # Modify the final classifier layer for binary classification
    # MobileNetV3's classifier is a Sequential block; the last layer is a Linear layer
    in_features = model.classifier[3].in_features
    model.classifier[3] = nn.Linear(in_features, 1)

    return model

# Initialize and move to your T4 GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = get_smile_model().to(device)

# Standard binary classification setup
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# Example dummy forward pass to test architecture
dummy_input = torch.randn(16, 3, 224, 224).to(device) # Batch of 16 images
logits = model(dummy_input) # Outputs shape: [16, 1]

# Example loss calculation
dummy_labels = torch.empty(16, 1).random_(2).to(device) # 0s and 1s
loss = criterion(logits, dummy_labels)
print(f"Initial loss: {loss.item()}")

# This will print the exact content of your current Colab notebook
!cat /content/*.ipynb 2>/dev/null || cat *.ipynb



